<!DOCTYPE Sistema [
<!ELEMENT Sistema (Usuarios)>
<!ELEMENT Usuarios (Usuario+)>
<!ELEMENT Usuario (Nombre , Contra , Rol,Correo)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Contra (#PCDATA)>
<!ELEMENT Correo (#PCDATA)>
<!ELEMENT Rol (#PCDATA)>
]>
<Sistema>
	<Usuarios>
            <Usuario>
                <Nombre>Eric Uriel Trejo Trejo</Nombre>
                <Contra>123123123</Contra>
                <Rol>1</Rol>
                <Correo>ericto117@gmail.com</Correo>
            </Usuario>
	</Usuarios>
</Sistema>
